### PR TITLE
Add unweighted sample

### PR DESCRIPTION
**Pull request by rstub**
c.f. #21 

- [x] Long vector support
- [x] Hash based algorithm for ~large input vectors~ low selection rates w/o replacement

### CODE REVIEW

**Comment by rstub** [comment]
Benchmarks for sampling with replacement:

``` r
library(dqrng)
m <- 1e7
n <- 1e5
bm <- bench::mark(sample.int(m, n, replace = TRUE),
                  sample.int(1e3*m, n, replace = TRUE),
                  dqsample.int(m, n, replace = TRUE),
                  dqsample.int(1e3*m, n, replace = TRUE),
                  check = FALSE)
bm[, 1:6]
#> # A tibble: 4 x 6
#>   expression                       min     mean   median      max `itr/sec`
#>   <chr>                       <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl>
#> 1 sample.int(m, n, replace =…   1.05ms    1.2ms   1.18ms   1.89ms      832.
#> 2 sample.int(1000 * m, n, re…   1.69ms   2.07ms   2.03ms   3.16ms      484.
#> 3 dqsample.int(m, n, replace… 326.24µs 367.82µs 351.99µs 617.77µs     2719.
#> 4 dqsample.int(1000 * m, n, … 374.68µs  423.9µs 394.82µs 977.58µs     2359.
plot(bm)
```



<sup>Created on 2019-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Sampling from 10^7 elements triggers the "normal" function, while sampling from 10^10 elements triggers the function for long vector support, even though the resulting vector is always a "normal" one.

**Comment by rstub** [comment]
# Benchmarks for sampling without replacement

## Selecting 1% of a "normal" vector

``` r
library(dqrng)
m <- 1e7
n <- 1e5
bm <- bench::mark(sample.int(m, n),
                  sample.int(m, n, useHash = TRUE),
                  dqsample.int(m, n),
                  check = FALSE)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
bm[, 1:6]
#> # A tibble: 3 x 6
#>   expression                        min     mean   median     max `itr/sec`
#>   <chr>                        <bch:tm> <bch:tm> <bch:tm> <bch:t>     <dbl>
#> 1 sample.int(m, n)              23.08ms  25.33ms  23.48ms  54.2ms      39.5
#> 2 sample.int(m, n, useHash = …    3.4ms   3.88ms   3.67ms   7.8ms     257. 
#> 3 dqsample.int(m, n)             1.18ms   1.38ms   1.24ms   4.4ms     726.
plot(bm)
```



<sup>Created on 2019-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

* R does not use it's hashset based algorithm, even though that is faster than the default.
* The bitset in `dqrng` is even faster, though.

## Selecting 60% of a "normal" vector

``` r
library(dqrng)
m <- 1e7
n <- 6e6
bm <- bench::mark(sample.int(m, n),
                  dqsample.int(m, n),
                  check = FALSE, min_iterations = 20)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
bm[, 1:6]
#> # A tibble: 2 x 6
#>   expression              min     mean   median      max `itr/sec`
#>   <chr>              <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl>
#> 1 sample.int(m, n)      363ms    374ms    372ms    407ms      2.67
#> 2 dqsample.int(m, n)    204ms    214ms    214ms    221ms      4.67
plot(bm)
```



<sup>Created on 2019-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## Selecting 0.001% of a "normal" vector

``` r
library(dqrng)
m <- 1e7
n <- 1e2
bm <- bench::mark(sample.int(m, n),
                  sample.int(m, n, useHash = TRUE),
                  dqsample.int(m, n),
                  check = FALSE)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
bm[, 1:6]
#> # A tibble: 3 x 6
#>   expression                        min     mean   median     max `itr/sec`
#>   <chr>                        <bch:tm> <bch:tm> <bch:tm> <bch:t>     <dbl>
#> 1 sample.int(m, n)              18.18ms  19.91ms  18.59ms 46.39ms      50.2
#> 2 sample.int(m, n, useHash = …    3.9µs   6.29µs   5.63µs  3.36ms  159038. 
#> 3 dqsample.int(m, n)             3.62µs    4.7µs   4.12µs  2.11ms  212832.
plot(bm)
```



<sup>Created on 2019-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

* R does not use it's hashset based algorithm, even though that is faster than the default.
* The hashset in `dqrng` has comparable speed.

## Selecting 0.001% of a "long" vector

``` r
library(dqrng)
m <- 1e10
n <- 1e5
bm <- bench::mark(sample.int(m, n),
                  dqsample.int(m, n),
                  check = FALSE)
bm[, 1:6]
#> # A tibble: 2 x 6
#>   expression              min     mean   median      max `itr/sec`
#>   <chr>              <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl>
#> 1 sample.int(m, n)     5.38ms   5.96ms   5.63ms  10.64ms      168.
#> 2 dqsample.int(m, n)   1.78ms   2.23ms    2.1ms   4.96ms      448.
plot(bm)
```



<sup>Created on 2019-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by LTLA** [comment]
Sweet. It's a shame that I have to deal with a non-standard formulation of the downsampling problem in `DropletUtils::downsampleReads`, otherwise I would be tempted to plug in these functions.

**Comment by rstub** [comment]
@LTLA In what way is your downsampling problem non-standard?

**Comment by LTLA** [comment]
Ah, it's pretty bespoke. The situation is that I have a vector of frequencies of categories (specifically, expression counts for genes) and need to downsample it without replacement. The trick is to avoid expanding the frequency vector into a vector of instances (i.e., keep it as `c(A=10, B=5)` rather than `rep(c("A", "B"), c(10, 5))`), both in the input and output of any hypothetical downsampling function. Parts of the downsampling are also performed in a semi-streaming manner because I don't have access to the entire vector in memory at any given time.

I wouldn't worry about it if I were you, it's probably too specific to write general code for.

**Comment by rstub** [comment]
That sounds very specific, indeed. Even so, faster random numbers can help even their. And I plan to implement scalar functions like `R:runif`  also in `dqrng`. No ETA, though.

**Pull request merged**
